  
# This is a basic workflow to help you get started with Actions


name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node
      
    - name: Install Yarn
      uses: borales/actions-yarn
      with:
        cmd: install
        
    - name: Install related libraries
      run: sudo yarn add @apollo/client graphql graphql-tag
      
    - name: Install surge
      run: sudo yarn global add surge
                  
    - name: Build React App
      run: yarn build
      
    - name: Deploy surge
      run: surge ./build asif_spacex.surge.sh --token ${{secrets.SURGE_TOKEN}}
